apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knfrouter.fullname" . }}
  labels:
    {{- include "knfrouter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "knfrouter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: extnet, internalnet-2
      labels:
        {{- include "knfrouter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knfrouter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["/bin/sleep", "3650d"] 
          command:
            - /bin/bash 
            - -exc
            - |
                /usr/share/openvswitch/scripts/ovs-ctl start
                ovs-vsctl add-br br1
                /sbin/ifconfig br1 192.168.255.1/24
                service isc-dhcp-server restart
                ovs-vsctl add-port br1 vxlan1 -- set interface vxlan1 type=vxlan options:remote_ip=192.168.16.1
                /usr/bin/vnx_config_nat br1 net1
                ip route del default
                ip route add 0.0.0.0/0 via 10.2.3.254 
                /bin/sleep 3650d
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
