---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: internalnet-1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth4",
      "mode": "bridge",
      "ipam": {
          "type": "static",
          "addresses": [
               {
                   "address": "192.168.16.1/24"
               }
          ]
       }
    }'
