---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: extnet
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "usbethpagoda.1",
      "mode": "bridge",
      "ipam": {
          "type": "static",
          "ranges": [
               {
                   "address": "10.2.3.1/24"
               }
          ]
       }
    }'
